### ISSUE TITLE
Errors reported by PowerShellGallery

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/cFSRM#1]
```
  Parse error in file ...\Documents\WindowsPowerShell\Modules\cDFS\1.4.0.66\Examples\Sample_DcFSNameSpace.ps1:  The string is missing the terminator: ' at line 30 column 82.Parse error in file ...\Documents\WindowsPowerShell\Modules\cDFS\1.4.0.66\Examples\Sample_DcFSNameSpace.ps1:  Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource  [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>] at line 3 column 24.Parse error in file ...\Documents\WindowsPowerShell\Modules\cDFS\1.4.0.66\Examples\Sample_DcFSNameSpace.ps1:  Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource  [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>] at line 30 column 41.Parse error in file ...\Documents\WindowsPowerShell\Modules\cDFS\1.4.0.66\Examples\Sample_DcFSNameSpace.ps1:  Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource  [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>] at line 30 column 51.Parse error in file ...\Documents\WindowsPowerShell\Modules\cDFS\1.4.0.66\Examples\Sample_DcFSNameSpace.ps1:  Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource  [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>] at line 30 column 55.Parse error in file ...\Documents\WindowsPowerShell\Modules\cDFS\1.4.0.66\Examples\Sample_DcFSNameSpace.ps1:  Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource  [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>] at line 30 column 63.Parse error in file ...\Documents\WindowsPowerShell\Modules\cDFS\1.4.0.66\Examples\Sample_DcFSNameSpace.ps1:  Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource  [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>] at line 30 column 72.Parse error in file ...\Documents\WindowsPowerShell\Modules\cDFS\1.4.0.66\Examples\Sample_DcFSNameSpace.ps1:  Missing closing '}' in statement block or type definition at line 2 column 1.
```

**Comment by PlagueHO** [comment]
Resolved.

**Comment by beugnen** [comment]
Hmmm....a year later and I'm getting this in Azure DSC

> Exception calling "NewScriptBlock" with "1" argument(s): "At line:9 char:24 + Import-DscResource �ModuleName 'PSDesiredStateConfiguration' + ~~~~~~~~~~~ **Positional parameters are not supported for the Import-DscResource dynamic keyword**. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>] At line:9 char:36 + Import-DscResource �ModuleName 'PSDesiredStateConfiguration' + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>]" (At line:9 char:24 + Import-DscResource �ModuleName 'PSDesiredStateConfiguration' + ~~~~~~~~~~~ Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: "Import-DscResource [-Name <ResourceName(s)>] [-ModuleName <ModuleName(s)>] [-ModuleVersion <ModuleVersion>] At line:9 char:36 + Import-DscResource �ModuleName 'PSDesiredStateConfiguration' + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Positional parameters are not supported for the Import-DscResource dynamic keyword. The syntax of Import-DscResource dynamic keyword is: 

This is the offending line:

    
`Import-DscResource -ModuleName 'xPSDesiredStateConfiguration'`

**Comment by beugnen** [comment]
oh skip that, turns out my file was not UTF-8-BOM and there was some mental � character in the file 

:)

**Comment by PlagueHO** [comment]
hehe no worries! Glad the problem didn't return :grin:
